# Generated by Django 5.1.2 on 2024-10-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoitem_description_todoitem_limitdate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='Task',
        ),
    ]
